site_name: Linear capturing types is all you need (for static memory management)
site_description: A thesis on static memory management in Scala.
site_url: 

# Using the popular Material theme
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: light blue
  features:
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

# Plugins
plugins:
  - search
  - print-site

# Navigation (Table of Contents)
nav:
  - Home: index.md
  - Introduction: introduction/index.md
  - Background:
    - Overview: background/index.md
    - Scala native: background/scala-native.md
    - Scala AST: background/scala-ast.md
    - Dependent types: background/dependent-types.md
    - Capturing types: background/capturing-types.md
    - Linear types: background/linear-types.md
    - Ownership: background/ownership.md
    - Stacked borrows: background/stacked-borrows.md

  - Scinear A linear type plugin for Scala:
    - Overview: scinear/index.md
    - Defining linear types: scinear/defining-linear-types.md
    - Using linear types: scinear/using-linear-types.md
    - Polymorphism: scinear/polymorphism.md
    - Capture checking: scinear/capture-checking.md
    - Memory model: scinear/memory-model.md
    - Plugin implementation: scinear/plugin-implementation.md
  - Static memory management library `imem`:
    - Overview: imem/index.md
    - Memory Management: imem/memory-management.md
    - Runtime: imem/runtime.md
    - Ownership: imem/ownership.md
    - Borrow checking: imem/borrow-checking.md
    - Discussion on soundness: imem/soundness.md
  - Evaluation:
    - Overview: evaluation/index.md
    - Baselines: evaluation/baselines.md
    - Case study: evaluation/case-study.md
  - Related works:
    - Overview: related-works/index.md
    - Dynamic memory management: related-works/dynamic-memory-management.md
    - Static memory management: related-works/static-memory-management.md
  - Conclusion: 
    - Overview: conclusion/index.md
    - Future work: conclusion/future-works.md

# Extensions for better Markdown and syntax highlighting
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - mdx_truly_sane_lists

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
